version: '3'
services:
  php-workspace:
    build: ./php
    volumes: # 这里指定数据卷，可以指定多个， 中划线代表值为数组的一个成员
      - ./code:/var/www/html
  nginx:
    build: ./nginx #这里nginx指我们的创建的目录
    ports:
      - "8080:8080"
  db:
    build: ./mysql
    command:  --default-authentication-plugin=mysql_native_password
    restart: always
    environment: # 设定环境变量，只给定名称的变量会自动获取运行 Compose 主机上对应变量的值
        MYSQL_ROOT_PASSWORD: root
  redis:
    build: ./redis