version: '3'
services:
  php-workspace:
    build: ./php56
    volumes: # 这里指定数据卷，可以指定多个， 中划线代表值为数组的一个成员
      - ./code:/var/www/html
    depends_on:  #指定依赖项，解决容器启动先后问题
      - db
      - redis
  php56:
    build: ./php56
    ports:
      - 9008:9000
    volumes:
      - /var/www/ecshop_online:/var/www/ecshop_online
      - /var/www/:/var/www/
    links:
      - db
  nginx:
    build: ./nginx #这里nginx指我们的创建的目录
    ports:
      - 80:80
      - 443:443
    volumes: 
      - /var/log/nginx:/var/log/nginx #增加本地和容器nginx目录映射
      - /var/www/:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - php56
  db:
    build: ./mysql
    command:  --default-authentication-plugin=mysql_native_password
    restart: always
    environment: # 设定环境变量，只给定名称的变量会自动获取运行 Compose 主机上对应变量的值
        MYSQL_ROOT_PASSWORD: root
  redis:
    build: ./redis